### ISSUE TITLE
처음시작을 JTextArea로 했는데 JTextPane으로 바꾸어야 할거 같습니다.

### ISSUE THREAD

**Issue by Baekinhyuk** [LDongGyu/CAU-SWengineering09#24]
JTextArea로 했는데 이거같은경우 속도가 빠른만큼 단순하게 텍스트를 쓸수있는데
JTextPane로 해야지 한 줄 한 줄 Compare 시 다른 경우 텍스트를 다르게 표시할수 있습니다.

**Comment by LDongGyu** [comment]
변경완료했습니다!
